### ISSUE TITLE
Incorrect permissions set on perl package blob

### ISSUE THREAD

**Issue by maximhan** [swisscom/mongodb-enterprise-boshrelease#7]
Hi!

It seems like the blob for `perl/perl-5.30.1.tar.gz` has incorrect S3 permissions set, not allowing anonymous read access:

![image](https://user-images.githubusercontent.com/264774/106049483-6f3dd580-60e6-11eb-8962-4104585117fb.png)

The remaining packages work fine (`net-snmp/net-snmp-5.7.3.tar.gz` and `ruby/ruby-2.3.2.tar.gz`).

This prevents the release from being uploaded to BOSH without modifying the blobstore location, and manually overriding the packages.

**Comment by Lafunamor** [comment]
Hi @maximhan 

Thank you for bringing this to our attention. Can you please try again?

**Comment by meraj-kashi** [comment]
Hi, Thank. it is accessible now.
